name: Delete old workflow

permissions:
  actions: write
  contents: read

on:
  schedule:
    # Run at midnight every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  call-workflow:
    uses: Robotsix-UAV/robotsix_workflows/.github/workflows/delete-old-workflow.yaml@main

