# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  call-workflow:
    uses: Robotsix-UAV/robotsix_workflows/.github/workflows/deploy-pages.yaml@main
